### Site Settings ###
title               : wannahack.in
description         : "qqq adfsdaf"
baseurl             : ""                                  # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : NaNameUz3r/NaNameUz3r.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/projects.html
  - pages/about.md


### Author Info ###
author:
  name              : Ivan Zakutnii
  image             : https://avatars.githubusercontent.com/u/78234165?v=4
# behance           : your_username
# dribbble          : your_username
  telegram          : wannahackin
  github            : NaNameUz3r
  linkedin          : ivan-zakutnii-a43851203
  email             : zakutnii.ivan@gmail.com
# facebook          : your_username
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-H7F0WEEGDF


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: true
  username: ivanzakutn11
  color: "#007bff"
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
